kind: pipeline
type: docker
name: deploy-onboardix

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: glsvitoria/onboardix
      tags: 1.0
      cache_from: glsvitoria/onboardix:1.0
      cache_to: glsvitoria/onboardix:1.0,mode=max

  - name: deploy-to-server
    image: docker:23
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: project-files
        path: /app
    commands:
      - apk add --no-cache docker-cli-compose
      - cd /app
      - docker compose -p onboardix --env-file .env pull
      - docker compose -p onboardix --env-file .env down --remove-orphans || true
      - docker compose -p onboardix --env-file .env up -d --force-recreate --remove-orphans

  - name: notificar-falha-discord
    image: appleboy/drone-discord
    settings:
      webhook_url:
        from_secret: discord_webhook
      message: '🚨 Falha no pipeline do repositório **${DRONE_REPO}** na branch **${DRONE_BRANCH}**.'
    when:
      status:
        - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: project-files
    host:
      path: /home/cedraz-ubuntu-2/Documentos/deploys/onboardix

trigger:
  branch:
    - main
  event:
    - push